In [387]:
import gym
import numpy as np

In [388]:
env = gym.make('FrozenLake8x8-v0')

In [389]:
def value_iteration(env, gamma = 1.0, no_of_iterations = 10000):
    optimal_value_table = np.zeros(env.observation_space.n)
    threshold = 1e-20
    
    #Mencari optimal value function
    for i in range (no_of_iterations):
        prev_value_table = np.copy(optimal_value_table)
        for state in range(env.observation_space.n):
            Q_value = np.zeros(env.action_space.n) #banyaknya elemen sesuai dengan banyaknya action pada state
            for action in range (env.action_space.n):
                for next_sr in env.P[state][action]: #next_sr adalah kemungkinan transisi jika action dilakukan pd state
                    trans_prob, next_state, reward_prob, _ = next_sr
                    Q_value[action] += trans_prob * (reward_prob + gamma * optimal_value_table[next_state])
            optimal_value_table[state] = max(Q_value)

        if np.sum(np.fabs(prev_value_table - optimal_value_table)) <= threshold :
            print ('Value iteration converged at iteration# %d ' %(i+1) )
            break
            
    #Mencari optimal policy
    policy = np.zeros(env.observation_space.n)
    for state in range(env.observation_space.n):
        Q_value = np.zeros(env.action_space.n)
        for action in range (env.action_space.n):
            for next_sr in env.P[state][action]:
                trans_prob, next_state, reward_prob, _ = next_sr
                Q_value[action] += (trans_prob * (reward_prob + gamma * optimal_value_table[next_state]))
        policy[state] = np.argmax(Q_value)
    
            
    return optimal_value_table, policy

In [390]:
value_table, policy = value_iteration(env)
print(value_table, '\n', policy)

Value iteration converged at iteration# 1676 
[1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         0.97820163
 0.92643052 0.         0.85661768 0.94623163 0.98207721 1.
 1.         0.9346049  0.80108992 0.47490377 0.6236214  0.
 0.94467761 1.         1.         0.82561308 0.54223433 0.
 0.53934275 0.61118923 0.85195561 1.         1.         0.
 0.         0.16804079 0.38321763 0.44226934 0.         1.
 1.         0.         0.19467347 0.12090475 0.         0.33240114
 0.         1.         1.         0.73155782 0.46311564 0.
 0.27746705 0.5549341  0.77746705 0.        ] 
 [1. 2. 2. 1. 2. 2. 2. 2. 3. 3. 3. 3. 3. 3. 3. 2. 0. 0. 0. 0. 2. 3. 3. 2.
 0. 0. 0. 1. 0. 0. 2. 2. 0. 3. 0. 0. 2. 1. 3. 2. 0. 0. 0. 1. 3. 0. 0. 2.
 0. 0. 1. 0. 0. 0. 0. 2. 0. 1. 0. 0. 1. 2. 1. 0.]


In [391]:
simulation(env, policy)


SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

  (Down)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

  (Down)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

  (Right)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

  (Down)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

  (Up)
SFFFFFFF
FFFFFFFF
FFFHFFFF
FFFFFHFF
FFFHFFFF
FHHFFFHF
FHFFHFHF
FFFHFFFG

  (Down)
SFFFFFFF
FFFFFFF

In [392]:
def policy_evaluation(env, policy, gamma = 1.0):
    threshold = 1e-10
    no_of_iterations = 10000
    value_table = np.zeros(env.observation_space.n)
    for i in range (no_of_iterations):
        prev_value_table = np.copy(value_table)
        for state in range(env.observation_space.n):
            action = policy[state]
            value_table[state] = sum([trans_prob * (reward_prob + gamma * value_table[next_state])
                                     for trans_prob, next_state, reward_prob, _ in env.P[state][action]])
            
            '''
            Kalo policy nya stochastic
            temp = 0
            for action, prob_action in policy[state]:
                temp += prob_action * sum([trans_prob * (reward_prob + gamma * value_table[next_state])
                                     for trans_prob, next_state, reward_prob, _ in env.P[state][action]])
            value_table[state] = temp
            '''              
        if max(np.fabs(value_table - prev_value_table)) <= threshold:
            #print ('policy evaluation converged at iteration# %d ' %(i+1))
            break
    
    return value_table

def policy_improvement(env, value_table, gamma = 1.0) :
    policy = np.zeros(env.observation_space.n)
    for state in range (env.observation_space.n):
        Q_value = []
        for action in range(env.action_space.n):
            Q_action_state = np.sum([trans_prob * (reward_prob + gamma * value_table[next_state])
                              for trans_prob, next_state, reward_prob, _ in env.P[state][action]])
            Q_value.append(Q_action_state)
        policy[state] = np.argmax(Q_value)
    return policy

def policy_iteration(env, gamma = 1.0):
    no_of_iterations = 10000
    policy = np.zeros(env.observation_space.n)
    for i in range (no_of_iterations):
        prev_policy = np.copy(policy)
        value_table = policy_evaluation(env, policy)
        policy = policy_improvement(env, value_table)
        if (np.array_equal(policy, prev_policy)):
            print ('policy iteration converged at iteration# %d ' %(i+1))
            break
    return value_table, policy

In [393]:
policy_iteration(env)

policy iteration converged at iteration# 13 


(array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 0.97820163, 0.92643052, 0.        ,
        0.85661768, 0.94623163, 0.98207721, 1.        , 1.        ,
        0.9346049 , 0.80108992, 0.47490377, 0.6236214 , 0.        ,
        0.94467761, 1.        , 1.        , 0.82561308, 0.54223433,
        0.        , 0.53934275, 0.61118923, 0.85195561, 1.        ,
        1.        , 0.        , 0.        , 0.16804079, 0.38321763,
        0.44226934, 0.        , 1.        , 1.        , 0.        ,
        0.19467346, 0.12090475, 0.        , 0.33240114, 0.        ,
        1.        , 1.        , 0.73155782, 0.46311564, 0.        ,
        0.27746705, 0.5549341 , 0.77746705, 0.        ]),
 array([1., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 2., 0.,
        0., 0., 0., 2., 3., 3., 2., 0., 0., 0., 1.

In [394]:
value_iteration(env)

Value iteration converged at iteration# 1676 


(array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 0.97820163, 0.92643052, 0.        ,
        0.85661768, 0.94623163, 0.98207721, 1.        , 1.        ,
        0.9346049 , 0.80108992, 0.47490377, 0.6236214 , 0.        ,
        0.94467761, 1.        , 1.        , 0.82561308, 0.54223433,
        0.        , 0.53934275, 0.61118923, 0.85195561, 1.        ,
        1.        , 0.        , 0.        , 0.16804079, 0.38321763,
        0.44226934, 0.        , 1.        , 1.        , 0.        ,
        0.19467347, 0.12090475, 0.        , 0.33240114, 0.        ,
        1.        , 1.        , 0.73155782, 0.46311564, 0.        ,
        0.27746705, 0.5549341 , 0.77746705, 0.        ]),
 array([1., 2., 2., 1., 2., 2., 2., 2., 3., 3., 3., 3., 3., 3., 3., 2., 0.,
        0., 0., 0., 2., 3., 3., 2., 0., 0., 0., 1.